In [29]:
import pandas as pd
import numpy as np

games_url = 'https://andybek.com/pandas-games'
games = pd.read_csv(games_url)

studios = games.loc[:, ['Genre', 'Publisher', 'Global_Sales']]

studios.groupby('Publisher')['Global_Sales'].agg(['sum', 'max', 'min', 'count']).sort_values('sum', ascending=False)

studios.groupby(['Genre', 'Publisher']).agg(['sum', 'count', 'mean', 'std'])\
       .rename({'sum': 'total_revenue', 'count': 'num_games'}, axis=1)

studios.groupby(['Genre', 'Publisher']).agg(
    total_revenue=('Global_Sales','sum'), 
    num_games=('Global_Sales', np.mean),
    revenue_std=('Global_Sales', 'std'),
    revenue_avg=('Global_Sales', 'mean')
    ).sort_values(by='total_revenue', ascending=False)

In [44]:


studios.groupby(['Genre', 'Publisher']).agg(['sum', 'count', 'mean', 'std'])\
       .rename({'sum': 'total_revenue', 'count': 'num_games'}, axis=1)

studios.groupby(['Genre', 'Publisher']).agg(
    total_revenue=('Global_Sales','sum'), 
    num_games=('Global_Sales', np.mean),
    revenue_std=('Global_Sales', 'std'),
    revenue_avg=('Global_Sales', 'mean')
    ).sort_values(by='total_revenue', ascending=False)

                                         total_revenue  num_games  \
Genre        Publisher
Shooter      Activision                         245.46   3.409167
Sports       Electronic Arts                    203.50   1.197059
Action       Take-Two Interactive               106.04   4.610435
             Ubisoft                             96.44   1.439403
Shooter      Electronic Arts                     92.58   1.851600
...                                                ...        ...
Adventure    Cave                                 0.01   0.010000
Role-Playing TopWare Interactive                  0.01   0.010000
Sports       Interworks Unlimited, Inc.           0.01   0.010000
Strategy     Ackkstudios                          0.01   0.010000
Adventure    Views                                0.01   0.010000

                                         revenue_std  revenue_avg
Genre        Publisher
Shooter      Activision                     4.621920     3.409167
Sports       Electronic Arts                1.404108     1.197059
Action       Take-Two Interactive           5.843768     4.610435
             Ubisoft                        1.636460     1.439403
Shooter      Electronic Arts                1.794404     1.851600
...                                              ...          ...
Adventure    Cave                                NaN     0.010000
Role-Playing TopWare Interactive                 NaN     0.010000
Sports       Interworks Unlimited, Inc.          NaN     0.010000
Strategy     Ackkstudios                         NaN     0.010000
Adventure    Views                               NaN     0.010000

[422 rows x 4 columns]

In [ ]:
studios.groupby(['Genre', 'Publisher']).agg(['sum', 'std'])