In [52]:
import pandas as pd
import numpy as np

tech_url = 'https://andybek.com/pandas-tech'
tech = pd.read_csv(tech_url, index_col=['date', 'name'])

# select a list of dates and a list of stocks, and all columns. 
# Note the list of stocks and list of dates are enclosed in a touple
tech.loc[(['2015-01-06', '2015-01-07'], ['FB', 'AMZN']), :]
# selecting only a list of columns
tech.loc[(['2014-01-02', '2014-01-03'], ['AAPL', 'MSFT', 'AMZN']), ['close', 'volume']]

tech.loc[(['2014-01-02', '2014-01-03'], ['AAPL', 'MSFT', 'AMZN']), 'open': 'low']

# slicing does not work as expected. slice is needed
# slice object is used to slice a milti index dataframe
tech.loc[(slice('2014-01-02', '2014-03-03'), ['GOOGL', 'MSFT']), 'open': 'low']
# select all dates 
tech.loc[(slice(None), ['FB', 'AMZN']), 'open']

date        name
2014-01-02  FB        54.86
2014-01-03  FB        55.00
2014-01-06  FB        54.39
2014-01-07  FB        57.67
2014-01-08  FB        57.59
                     ...
2019-08-19  AMZN    1818.08
2019-08-20  AMZN    1814.50
2019-08-21  AMZN    1819.39
2019-08-22  AMZN    1828.00
2019-08-23  AMZN    1793.03
Name: open, Length: 2842, dtype: float64

In [43]:
tech.loc[(['2015-01-06', '2015-01-07'], ['FB', 'AMZN']), ['close', 'volume']]

                  close    volume
date       name
2015-01-06 FB     76.15  27399288
           AMZN  295.29   3519034
2015-01-07 FB     76.15  22045333
           AMZN  298.42   2640349

In [25]:
tech.head(50)

                  month  year  day    open   close    high     low    volume  \
date       name
2014-01-02 FB         1  2014    2   54.86   54.71   55.22   54.19  43257622
           AAPL       1  2014    2   79.38   79.02   79.58   78.86   8398851
           GOOGL      1  2014    2  557.73  556.56  558.88  554.13   1822719
           MSFT       1  2014    2   37.35   37.16   37.40   37.10  30643745
           AMZN       1  2014    2  398.80  397.97  399.36  394.02   2140246
2014-01-03 FB         1  2014    3   55.00   54.56   55.65   54.53  38287706
           GOOGL      1  2014    3  557.50  552.50  558.47  552.47   1669229
           MSFT       1  2014    3   37.20   36.91   37.22   36.60  31134795
           AAPL       1  2014    3   79.00   77.28   79.10   77.20  14043410
           AMZN       1  2014    3  398.29  396.44  402.71  396.22   2213512
2014-01-06 MSFT       1  2014    6   36.86   36.13   36.89   36.11  43615035
           AMZN       1  2014    6  396.13  393.63  397.00  388.42   3172207
           AAPL       1  2014    6   76.78   77.70   78.11   76.23  14765593
           GOOGL      1  2014    6  556.51  558.66  559.43  553.22   1770782
           FB         1  2014    6   54.39   57.20   57.26   54.05  68974359
2014-01-07 FB         1  2014    7   57.67   57.92   58.55   57.22  77329009
           AAPL       1  2014    7   77.76   77.15   77.99   76.85  11347538
           MSFT       1  2014    7   36.30   36.41   36.49   36.21  35924726
           AMZN       1  2014    7  395.04  398.03  398.47  394.29   1916684
           GOOGL      1  2014    7  562.49  569.43  569.85  560.58   2553999
2014-01-08 AAPL       1  2014    8   76.97   77.64   77.94   76.96   9240955
           AMZN       1  2014    8  398.47  401.92  403.00  396.04   2316903
           MSFT       1  2014    8   36.05   35.76   36.14   35.58  59979542
           GOOGL      1  2014    8  573.66  570.62  573.66  566.65   2243444
           FB         1  2014    8   57.59   58.23   58.41   57.23  56800776
2014-01-09 AAPL       1  2014    9   78.11   76.65   78.12   76.48   9986457
           AMZN       1  2014    9  403.75  401.01  406.89  398.44   2103793
           GOOGL      1  2014    9  571.62  565.12  572.11  562.78   2085565
           FB         1  2014    9   58.66   57.22   58.96   56.65  92349222
           MSFT       1  2014    9   35.88   35.53   35.91   35.40  36520448
2014-01-10 AAPL       1  2014   10   77.12   76.13   77.26   75.87  10902952
           GOOGL      1  2014   10  569.54  565.09  569.54  561.13   2145560
           MSFT       1  2014   10   35.94   36.04   36.15   35.75  40558766
           FB         1  2014   10   57.13   57.94   58.30   57.06  42529258
           AMZN       1  2014   10  402.04  397.66  403.76  393.80   2681701
2014-01-13 AAPL       1  2014   13   75.71   76.53   77.50   75.70  13551549
           MSFT       1  2014   13   36.00   34.98   36.02   34.83  45923872
           GOOGL      1  2014   13  563.28  561.49  573.45  558.59   2425615
           FB         1  2014   13   57.89   55.91   58.25   55.38  63106519
           AMZN       1  2014   13  397.67  390.98  399.78  388.45   2846507
2014-01-14 FB         1  2014   14   56.48   57.74   57.78   56.10  37590987
           AAPL       1  2014   14   76.86   78.06   78.10   76.81  11962053
           GOOGL      1  2014   14  568.98  574.70  575.50  564.04   2484514
           MSFT       1  2014   14   34.71   35.78   35.88   34.63  41627325
           AMZN       1  2014   14  392.13  397.54  398.63  391.29   2340401
2014-01-15 AMZN       1  2014   15  398.94  395.87  399.31  392.53   2678794
           FB         1  2014   15   58.00   57.60   58.57   57.27  33730619
           GOOGL      1  2014   15  576.50  574.31  577.50  571.90   1951012
           AAPL       1  2014   15   79.07   79.62   80.03   78.81  14067517
           MSFT       1  2014   15   35.91   36.76   36.79   35.85  44909545

                 volume_type
date       name
2014-01-02 FB         medium
           AAPL          low
           GOOGL      medium
           MSFT       medium
           AMZN       medium
2014-01-03 FB         medium
           GOOGL      medium
           MSFT       medium
           AAPL          low
           AMZN       medium
2014-01-06 MSFT       medium
           AMZN       medium
           AAPL          low
           GOOGL      medium
           FB           high
2014-01-07 FB           high
           AAPL          low
           MSFT       medium
           AMZN          low
           GOOGL      medium
2014-01-08 AAPL          low
           AMZN       medium
           MSFT       medium
           GOOGL      medium
           FB           high
2014-01-09 AAPL          low
           AMZN          low
           GOOGL      medium
           FB           high
           MSFT       medium
2014-01-10 AAPL          low
           GOOGL      medium
           MSFT       medium
           FB         medium
           AMZN       medium
2014-01-13 AAPL          low
           MSFT       medium
           GOOGL      medium
           FB           high
           AMZN       medium
2014-01-14 FB         medium
           AAPL          low
           GOOGL      medium
           MSFT       medium
           AMZN       medium
2014-01-15 AMZN       medium
           FB         medium
           GOOGL      medium
           AAPL          low
           MSFT       medium

In [19]:
tech.loc[('2019-08-23', 'MSFT'), 'open':'close']

open     137.19
close    133.39
Name: (2019-08-23, MSFT), dtype: float64